//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IRF_beadando
{
    using System;
    using System.Collections.Generic;
    
    public partial class Eredmeny
    {
        public int EREDMENY_ID { get; set; }
        public string SFELH_NEV_FK { get; set; }
        public string EDZO_FELH_NEV_FK { get; set; }
        public System.DateTime DATUM { get; set; }
        public Nullable<int> PONT { get; set; }
    
        public virtual Edzo Edzo { get; set; }
        public virtual Sportolo Sportolo { get; set; }
    }
}
