//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IRF_beadando
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sportolo
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Sportolo()
        {
            this.Eredmenies = new HashSet<Eredmeny>();
        }
    
        public string SFELH_NEV { get; set; }
        public string SNEV { get; set; }
        public System.DateTime SZULDAT { get; set; }
        public string EDZO_FK { get; set; }
    
        public virtual Edzo Edzo { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Eredmeny> Eredmenies { get; set; }
    }
}
